language: node_js
node_js:
  -  "12"

before_script:

  # install v6.x of nodejs
   - nvm install 12
  #install yarn globally
   - npm install -g yarn
  # yarn install is like npm install
   - yarn install

jobs:
  include:
    - stage: npm release
      node_js: "12"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release
